provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  timezone-shift-convertor:
    lang: node10-express
    handler: ./timezone-shift-convertor
    image: timezone-shift-convertor:latest
